### ISSUE TITLE
Allow the personalization of the appearance and content of output messages.

### ISSUE THREAD

**Issue by byteveil** [lewmilburn/Essence#11]
I'd like to be able to completely customize the output messages that appear, such as the color formatting and the exact messages that are displayed after a command. I've tried creating a local copy of the project and doing it myself, but I have no Java experience.

**Comment by lewmilburn** [comment]
Hi, thanks for using essence! I should have time to add this later today :) I'll send a message on here when it's in. Thanks!

**Comment by lewmilburn** [comment]
Hi, I've added the functionality, I've just got a lecture to go to then when I get back I'll test and release it :)

**Comment by lewmilburn** [comment]
https://www.spigotmc.org/resources/essence.114553/, please let me know if you have any issues :) Thanks for the suggestion!

**Comment by lewmilburn** [comment]
https://wiki.lewmc.net/index.php/Customising_Essence_Messages

**Comment by byteveil** [comment]
This works amazingly, thank you very much. ❤️

![image](https://github.com/lewmilburn/Essence/assets/152559788/561a2392-418b-48ac-8286-464d0e442843)

**Comment by lewmilburn** [comment]
That's great to hear! No problem, if you have any more suggestions please feel free to open an issue for them and I'll be happy to take a look 😄

**Comment by byteveil** [comment]
> That's great to hear! No problem, if you have any more suggestions please feel free to open an issue for them and I'll be happy to take a look 😄 

I'm looking forward to doing that!
