### ISSUE TITLE
Allow use of player selectors (@a, @e, @s) in commands.

### ISSUE THREAD

**Issue by lewmilburn** [lewmilburn/Essence#13]

**Comment by byteveil** [comment]
This functionality should be optional. I may not plan to use it immediately and prefer the player name selector.

**Comment by byteveil** [comment]
If this doesn't go as optional can there be a command failsafe so if you use an invalid attribute in the selector (@e[type=etc] where type doesn't exist) it would prevent the running of the command and say that a type attribute is not available.

**Comment by lewmilburn** [comment]
> This functionality should be optional. I may not plan to use it immediately and prefer the player name selector.

Sure! I’ll make sure to have it via a configuration option
