### ISSUE TITLE
Minimal factions functionality.

### ISSUE THREAD

**Issue by byteveil** [lewmilburn/Essence#14]
I'd like to have a way to manage people in groups, and there aren't many good plugins out there that do that very well but I can see Essence having a good place with this feature.

The commands could be something like these:

- `/essence:group create [name]` ~ creates a group with the name if that group name is not taken
- `/essence:group join [name]` ~ sends a request to join the group (group members only, group creator would be told that they cannot join their own group)
- `/essence:group kick [name]` ~ kicks a player out of the group (group creator only)
- `/essence:group rule allowFriendlyFire true` ~ allowFriendlyFire is an example name but this would be a great feature to have friendly fire built-in, if `true` is not provided then it would just provide the current state of the rule. Rule configuration can either be available for OPs or just normal players depending on how people want their server to be.

I hope this is a good suggestion.

**Comment by lewmilburn** [comment]
Brilliant idea! I’ll get that in the next update - could take some time though!

**Comment by byteveil** [comment]
Some other commands may include:

- `/essence:group home [name]`
- `/essence:group sethome [name]`
- `/essence:group delhome [name]`
- `/essence:group homes`

**Comment by lewmilburn** [comment]
> Some other commands may include:
> 
> * `/essence:group home [name]`
> * `/essence:group sethome [name]`
> * `/essence:group delhome [name]`
> * `/essence:group homes`

Opened as #23

**Comment by lewmilburn** [comment]
Hi, I've uploaded a snapshot version (may contain bugs) to Hangar, Modrinth, and GitHub. If you give it a try let me know what you think. https://hangar.papermc.io/LewMC/Essence/versions/1.3.0-SNAPSHOT
