### ISSUE TITLE
Section in the configuration file to completely disable particular commands.

### ISSUE THREAD

**Issue by byteveil** [lewmilburn/Essence#19]
You could add a section in the configuration file (config.yml) to disable particular commands so that they don't show up on the auto-complete or initialize at all, this would be really useful if you have particular commands you want players to see and other commands you don't want them to see, and is also very useful if you prefer the built-in `/gamemode` command over the Essence `/gamemode` command.

These are just examples but I believe this would be a great management feature.

**Comment by lewmilburn** [comment]
Hi, I've added what I can in that regard, there are some limitations to the approach though and nothing I can do about it. I've put info on https://wiki.lewmc.net/index.php/Disabling_Commands

**Comment by byteveil** [comment]
> Hi, I've added what I can in that regard, there are some limitations to the approach though and nothing I can do about it. I've put info on https://wiki.lewmc.net/index.php/Disabling_Commands

Okay, thanks for the information. Learning new things as I go about making suggestions.
